#trigger:
#  branches:
#    include:
#      - main

resources:
  pipelines:
    - pipeline: frontend-ci
      source: frontend-ci
      trigger:
        branches:
          include:
            - main

pr: none

variables:
  myServiceConnection: "MyAzureServiceConnection"
  resourceGroup: "rg-banking-app"
  appServiceName: "frontend-appservice"
  acrName: "bankingacr"                 
  imageName: "frontend-ci"
  imageTag: "v$(resources.pipeline.frontend-ci.runId)"

stages:
  - stage: Deploy
    displayName: "Deploy Frontend to Azure App Service (Container)"
    jobs:
      - job: DeployToAppService
        displayName: "Deploy container to App Service"
        pool:
          name: Default
        steps:
          - checkout: self

          # Resolve ACR login server and full image name, expose as pipeline variables
          - task: PowerShell@2
            displayName: "Resolve ACR login server and full image name"
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Resolving ACR login server..."
                $rawAcr = "$(acrName)"
                if ($rawAcr -match "\.") {
                  $acrLoginServer = $rawAcr
                } else {
                  $acrLoginServer = "$($rawAcr).azurecr.io"
                }
                $image = "$acrLoginServer/$(imageName):$(imageTag)"
                Write-Host "ACR login server: $acrLoginServer"
                Write-Host "Full image name: $image"
                Write-Host "##vso[task.setvariable variable=acrLoginServer]$acrLoginServer"
                Write-Host "##vso[task.setvariable variable=fullImageName]$image"

          # Run the PowerShell deployment script (file stored in repo)
          - task: AzurePowerShell@5
            displayName: "Deploy to App Service (call PS script)"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              ScriptType: "FilePath"
              ScriptPath: "./Pipelines/Deploy-To-AppService.ps1"
              ScriptArguments: '"$(resourceGroup)" "$(appServiceName)" "$(acrLoginServer)" "$(imageName)" "$(imageTag)"'
              azurePowerShellVersion: "LatestVersion"
