# frontend-CD.yaml
resources:
  pipelines:
    - pipeline: frontend-ci
      source: frontend-ci
      trigger:
        branches:
          include:
            - main

pr: none

variables:
  myServiceConnection: "MyAzureServiceConnection"
  resourceGroup: "rg-banking-app"
  webAppName: "banking-app"
  acrName: "bankingacr"
  imageName: "frontend-ci"
  imageTag: "v$(resources.pipeline.frontend-ci.runId)"
  aksResourceGroup: "rg-banking-app"
  aksClusterName: "bankcluster"
  backendServiceName: "springboot-backend-service-prod"

stages:
  - stage: Deploy
    displayName: "Deploy Frontend to Azure App Service"
    jobs:
      - job: DeployFrontend
        displayName: "Deploy Frontend"
        pool:
          name: Default
        steps:
          - checkout: self

          # Login to Azure
          - task: AzureCLI@2
            displayName: "Login to Azure"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                az account show
            

          # # Fetch backend LoadBalancer IP
          # - task: AzureCLI@2
          #   displayName: "Fetch backend LoadBalancer IP"
          #   inputs:
          #     azureSubscription: "$(myServiceConnection)"
          #     scriptType: ps
          #     scriptLocation: inlineScript
          #     inlineScript: |
          #       Write-Host "Fetching backend LoadBalancer IP..."
          #       $lbIP = az aks command invoke `
          #         --resource-group $(aksResourceGroup) `
          #         --name $(aksClusterName) `
          #         --command "kubectl get svc $(backendServiceName) -o jsonpath='{.status.loadBalancer.ingress[0].ip}'" `
          #         --query "logs" -o tsv

          #       if ([string]::IsNullOrWhiteSpace($lbIP)) {
          #         Write-Host "  Failed to fetch backend LoadBalancer IP."
          #         exit 1
          #       }

          #       $backendURL = "http://4.224.75.153"
          #       Write-Host "  Backend API URL:$backendURL"
          #       Write-Host "##vso[task.setvariable variable=backendURL;]$backendURL"

          # Verify Docker image exists in ACR
          - task: AzureCLI@2
            displayName: "Verify ACR Image"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                $imagePath = "$(acrName).azurecr.io/$(imageName):$(imageTag)"
                Write-Host "Checking image existence: $imagePath"
                az acr repository show-tags --name $(acrName) --repository $(imageName) | Select-String $(imageTag)
                Write-Host " Image exists, proceeding to deployment..."

          # Deploy Docker image to Linux App Service and inject backend URL as App Setting
          - task: AzureWebAppContainer@1
            displayName: "Deploy Frontend to Linux App Service"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              appName: "$(webAppName)"
              resourceGroupName: "$(resourceGroup)"
              containers: |
                $(acrName).azurecr.io/$(imageName):$(imageTag)
              # # appSettings: |
              VITE_API_BASE_URL: "http://4.224.75.153"
