# frontend-CD.yaml
# Trigger on successful completion of frontend CI pipeline
resources:
  pipelines:
    - pipeline: frontend-ci
      source: frontend-ci
      trigger:
        branches:
          include:
            - main

pr: none

variables:
  myServiceConnection: "MyAzureServiceConnection"
  resourceGroup: "rg-banking-app"
  webAppName: "banking-app"       
  acrName: "bankingacr"                    
  imageName: "frontend-ci"                
  imageTag: "v$(resources.pipeline.frontend-ci.runId)" 
  aksResourceGroup: "rg-banking-app"             
  aksClusterName: "bankcluster"          
  backendServiceName: "springboot-backend-service-prod"          # name of LoadBalancer service

stages:
  - stage: Deploy
    displayName: "Deploy Frontend to Azure App Service"
    jobs:
      - job: DeployFrontend
        displayName: "Deploy Frontend"
        pool:
          name: Default
        steps:
          - checkout: self

          # Login to Azure
          - task: AzureCLI@2
            displayName: "Login to Azure"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                az account show

          #  Fetch Kubernetes LoadBalancer IP
          - task: AzureCLI@2
            displayName: "Fetch Backend LoadBalancer IP"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials -n $(aksClusterName) -g $(aksResourceGroup) --overwrite-existing
                $lbIP = kubectl get svc $(backendServiceName) -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
                if (-not $lbIP) {
                    Write-Error " Failed to fetch LoadBalancer IP for backend service $(backendServiceName)"
                    exit 1
                }
                Write-Host " Backend LoadBalancer IP: $lbIP"
                Write-Host "##vso[task.setvariable variable=backendURL;]http://$lbIP:80"
   # or appropriate port

          # Verify ACR and image exist
          - task: AzureCLI@2
            displayName: "Verify ACR Image"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                $imagePath = "$(acrName).azurecr.io/$(imageName):$(imageTag)"
                Write-Host "Checking image existence: $imagePath"
                az acr repository show-tags --name $(acrName) --repository $(imageName) | Select-String $(imageTag)
                Write-Host "Image exists, proceeding to deployment..."

          # Deploy using PowerShell script
          - task: AzurePowerShell@5
            displayName: "Deploy Frontend to App Service"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              ScriptType: "FilePath"
              ScriptPath: "./Pipelines/Frontend-CD.ps1"
              ScriptArguments: "$(resourceGroup) $(webAppName) $(acrName) $(imageName) $(imageTag) $(backendURL)"
              azurePowerShellVersion: "LatestVersion"
