# frontend-CD.yaml
resources:
  pipelines:
    - pipeline: frontend-ci
      source: frontend-ci
      trigger:
        branches:
          include:
            - main

pr: none

variables:
  myServiceConnection: "MyAzureServiceConnection"
  resourceGroup: "rg-banking-app"
  webAppName: "banking-app"
  acrName: "bankingacr"
  imageName: "frontend-ci"
  imageTag: "v$(resources.pipeline.frontend-ci.runId)"
  aksResourceGroup: "rg-banking-app"
  aksClusterName: "bankcluster"
  backendServiceName: "springboot-backend-service-prod"

stages:
  - stage: Deploy
    displayName: "Deploy Frontend to Azure App Service"
    jobs:
      - job: DeployFrontend
        displayName: "Deploy Frontend"
        pool:
          name: Default
        steps:
          - checkout: self

          # Login to Azure
          - task: AzureCLI@2
            displayName: "Login to Azure"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                az account show

          # Fetch backend LoadBalancer IP and export as VITE_API_BASE_URL
          - task: AzureCLI@2
            displayName: "Fetch backend LoadBalancer IP and set as VITE_API_BASE_URL"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                Write-Host "Fetching backend LoadBalancer IP..."
                $lbIP = az aks command invoke `
                  --resource-group $(aksResourceGroup) `
                  --name $(aksClusterName) `
                  --command "kubectl get svc $(backendServiceName) -o jsonpath='{.status.loadBalancer.ingress[0].ip}'" `
                  --query "logs" -o tsv

                if ([string]::IsNullOrWhiteSpace($lbIP)) {
                  Write-Host " Failed to fetch backend LoadBalancer IP."
                  exit 1
                }

                Write-Host " Backend LoadBalancer IP: $lbIP"
                $backendURL = "http://$lbIP"
                Write-Host " Backend API URL: $backendURL"
                Write-Host "##vso[task.setvariable variable=backendURL;]$backendURL"
                Write-Host " Backend URL variable exported for next steps."

          - task: FileTransform@2
            displayName: "Replace VITE_API_BASE_URL in .env"
            inputs:
              folderPath: '$(System.DefaultWorkingDirectory)/src' 
              fileType: 'env'
              targetFiles: '**/.env'
          # Verify ACR image exists
          - task: AzureCLI@2
            displayName: "Verify ACR Image"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              scriptType: ps
              scriptLocation: inlineScript
              inlineScript: |
                $imagePath = "$(acrName).azurecr.io/$(imageName):$(imageTag)"
                Write-Host "Checking image existence: $imagePath"
                az acr repository show-tags --name $(acrName) --repository $(imageName) | Select-String $(imageTag)
                Write-Host "Image exists, proceeding to deployment..."

          # Deploy to App Service
          - task: AzurePowerShell@5
            displayName: "Deploy Frontend to App Service"
            inputs:
              azureSubscription: "$(myServiceConnection)"
              ScriptType: "FilePath"
              ScriptPath: "./Pipelines/Frontend-CD.ps1"
              ScriptArguments: "$(resourceGroup) $(webAppName) $(acrName) $(imageName) $(imageTag) $(backendURL)"
              azurePowerShellVersion: "LatestVersion"
