#trigger:
#  branches:
#    include:
#      - main

resources:
  pipelines:
    - pipeline: frontend-ci
      source: frontend-ci
      trigger:
        branches:
          include:
            - main

pr: none

variables:
  myServiceConnection: "MyAzureServiceConnection"
  resourceGroup: "rg-banking-app"
  appServiceName: "frontend-appservice"
  acrName: "bankingacr"                 
  imageName: "frontend-ci"
  imageTag: "v$(resources.pipeline.frontend-ci.runId)"

stages:
  - stage: Deploy
    displayName: "Deploy Frontend to Azure App Service"
    jobs:
      - job: DeployToAppService
        displayName: "Deploy container to App Service"
        pool:
          name: Default
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: DeployFrontend
            inputs:
              azureSubscript+ion: $(myServiceConnection)
              scriptType: 'ps'    
              scriptLocation: 'scriptPath'
              scriptPath: './Pipelines/Frontend-CD.ps1'
       
         
          